#! /bin/bash

#SBATCH -J aggregation-script
#SBATCH --mail-type=ALL
#SBATCH --mail-user=anclaro@iu.edu
#SBATCH -p general
#SBATCH -o %j.out
#SBATCH -t 2:00:00
#SBATCH --mem=32G
#SBATCH -A r00272
#SBATCH --cpus-per-task=30

domain="Mathematics"
years="5 6 7 8 9"

module load python/3.11
cd /N/project/backboneScience/unarXiv/data/
mkdir /N/project/backboneScience/unarXiv/data/mathematics_5_9
srun python aggregate.py -d "$domain" -y "$years"
srun python data_locations.py -d "$domain" -y "$years"
